### ISSUE TITLE
对于数据处理有一点不懂的地方

### ISSUE THREAD

**Issue by YHX-X** [jacobwwh/graphmatch_clone#4]
作者您好，我有一点疑惑的地方，想向您请教。BigCloneBench数据集中把克隆对分成了五种克隆类型，分别为：T1, T2, ST3, MT3, WT3/T4。您在实验中是将这五种类型统一看成是克隆对和非克隆对，并用1和-1来做标签，没有按他们具体是哪种克隆类型来做区分（因为第五种克隆类型占比98%多，所以其他类型的相对来说可以忽略不计）。请问我的理解是正确的吗？请您赐教。

**Comment by jacobwwh** [comment]
是的。

**Comment by YHX-X** [comment]
> 是的。

谢谢您
