### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by CommissarSilver** [jacobwwh/graphmatch_clone#7]
Hi.
Thank you for open-sourcing your work. I'm aiming to replicate your work however, the versions of the packages that are used are not specified. I've tried different version combinations however they don't seem to work with each other. Can you please indicate the exact version for each of the packages that you have used?

**Comment by AntonioBobadilla** [comment]
Hi.
 
I used this libraries on a virtual enviroment and it worked for me.

pycparser==2.21
torch==2.0.1
javalang==0.13.0
torch-geometric==1.3.1
anytree==2.8.0
torch-sparse==0.6.17
torch-scatter==2.1.1
torch-cluster==1.6.1

**Comment by CommissarSilver** [comment]
It's a little bit late but thank you @AntonioBobadilla
